# Check https://alacritty.org/config-alacritty.html to understand each config

import = [
    "~/.config/alacritty/themes/themes/night_owl.toml"
]

live_config_reload = true

# ENV
# All key-value pairs in the [env] section will be added as
# environment variables for any process spawned by Alacritty,
# including its shell. Some entries may override variables
# set by alacritty itself.
[env]

[window]

[scrolling]
history = 100000
multiplier = 3

[font.bold]
family = "FiraCode Nerd Font"
style = "FiraCode Nerd Font"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"
style = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"
style = "FiraCode Nerd Font"

[selection]
save_to_clipboard = true
